version: '3'
services:
  node-app:
    container_name: node-app
    image: node
    user: root
    command: ["/bin/bash","-lc" ,"npm i && npm start"]
    ports:
      - '5000:5000'
    depends_on:
      - mysql
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - ./.env.docker:/home/node/app/.env
    networks:
      - node-network
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Dhiwise
    networks:
      - node-network
volumes:
  dbdata:
networks:
  node-network:
    driver: bridge